### ISSUE TITLE
Text Translation API is not working this week

### ISSUE THREAD

**Issue by IvanParedes365** [MicrosoftTranslator/Text-Translation-API-V3-NodeJS#4]
Dear colleagues,

I'm testing your examples and result is the same as with my own code. It seems that something change in the backend because provided example is not working getting the same error as with my own code.

{
    "error": {
        "code": 401000,
        "message": "The request is not authorized because credentials are missing or invalid."
    }
}

Could you please check and advice?

Thanks,
Ivan Paredes

**Comment by KIONAPAC** [comment]
The same to me.
For long time.

**Comment by 9812334** [comment]
bump

**Comment by MohitDeshwal** [comment]
Simply add one header.
`Ocp-Apim-Subscription-Region`

**Comment by chriswendt1** [comment]
Thank you, Mohit, for the contribution.
